apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    kubevirt.io/domain: testvm-win-pass
  name: testvm-win-pass
spec:
  domain:
    clock:
      utc: {}
      timer:
        hpet:
          present: false
        pit:
          tickPolicy: delay
        rtc:
          tickPolicy: catchup
        hyperv: {}
    cpu:
      cores: 8
    features:
      acpi: {}
      apic: {}
      hyperv:
        relaxed: {}
        vapic: {}
        spinlocks:
          spinlocks: 8191
    resources:
      limits:
        nvidia.com/GK104GL_GRID_K520: 1
      requests:
        memory: 12Gi
        nvidia.com/GK104GL_GRID_K520: 1
    devices:
       disks:
       - disk:
           bus: sata
         name: rootdisk
       interfaces:
       - bridge: {}
         model: e1000
         name: default
  terminationGracePeriodSeconds: 0
  volumes:
  - name: rootdisk
    persistentVolumeClaim:
      claimName: win-pvc
  networks:
  - name: default
    pod: {}
